# Generated by Django 3.2.3 on 2021-05-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
